# Имя воркфлоу
name: PR Checks

# Триггер: запускать на создание или обновление Pull Request в ветку main
on:
  pull_request:
    branches:
      - main

jobs:
  # Задача для запуска линтера
  lint:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Включаем кеширование зависимостей

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Запускаем линтер
      - name: Run linter
        run: npm run lint

  # Задача для запуска тестов
  test:
    runs-on: ubuntu-latest
    steps:
      # Шаги 1-3 аналогичны задаче lint
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Шаг 4: Запускаем тесты
      - name: Run tests
        run: npm run test
