name: PR checks
on:
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --watchAll=false
      - name: Auto-approve                    
        if: github.event_name == 'pull_request'
        uses: hmarr/auto-approve-action@v3
        with:                                 
          github-token: ${{ secrets.GITHUB_TOKEN }}
