name: Deploy prod

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"
        default: 16
      issue-number:
        type: number
        required: true
        description: "Release Issue number id"
        default: 6

jobs:
  start_docker:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo usermod -aG docker ${USER}
            echo ${{ secrets.YC_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex
            
            docker pull cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ inputs.version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d --restart unless-stopped -p 3000:3000 cr.yandex/${{secrets.YC_REGISTRY_ID}}/app:${{ inputs.version }}_latest
            cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest"

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Сформировать тело комментария
        id: comment_body
        run: |
          BODY=$(cat <<EOF
          🚀 **Прод релиз \`${{ inputs.version }}\` выкачан**
          📅 Дата: ${{ steps.date.outputs.date }}
          👤 Автор: @${{ github.actor }}
          🐳 Контейнер: \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest\`
          🧠 Сервер: \`${{ secrets.SSH_HOST }}\`
          EOF
          )
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment to GitHub Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ inputs.issue-number }}
          body: ${{ steps.comment_body.outputs.body }}
