name: Deploy prod

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"
      issue-number:
        type: number
        required: true
        description: "Release Issue number id"

jobs:
  start_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Auth SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/secret_key
          chmod 600 ~/.ssh/secret_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/secret_key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<'EOF'
            echo "${{ secrets.YC_OAUTH_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
            docker rm -f ${{ secrets.YC_REGISTRY_ID }} || true
            docker run --name ${{ secrets.YC_REGISTRY_ID }} -d -p 3000:3000 \
            cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest
          EOF

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Сформировать тело комментария
        id: comment_body
        run: |
          BODY=$(cat <<EOF
          🚀 **Прод релиз \`${{ inputs.version }}\` выкачан**
          📅 Дата: ${{ steps.date.outputs.date }}
          👤 Автор: @${{ github.actor }}
          🐳 Контейнер: \`cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ inputs.version }}_latest\`
          🧠 Сервер: \`${{ secrets.SSH_HOST }}\`
          EOF
          )
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment to GitHub Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ inputs.issue-number }}
          body: ${{ steps.comment_body.outputs.body }}
